### ISSUE TITLE
Stop allowing property access via __getitem__/__setitem__

### ISSUE THREAD

**Issue by frewsxcv** [frewsxcv/python-geojson#41]
Backwards incompatible change

**Comment by JesseWeinstein** [comment]
Er, should this still be open?

**Comment by frewsxcv** [comment]
right now with this library, one can do both of these:

```python
In [12]: geojson.loads('{"type": "Feature","geometry": {"type": "Point","coordinates": [125.6, 10.1]},"properties": 
    ...: {"name": "Dinagat Islands"}}').type
Out[12]: 'Feature'

In [13]: geojson.loads('{"type": "Feature","geometry": {"type": "Point","coordinates": [125.6, 10.1]},"properties": 
    ...: {"name": "Dinagat Islands"}}')['type']
Out[13]: 'Feature'
```

when i first opened the issue, i had interest in wanting to disallow indexing the with `['type']` for the `geojson.feature.Feature` object (removing the `__getitem__` implementation). i don't feel strongly it should be removed, i'm okay keeping it if people want it. what do you think?

**Comment by JesseWeinstein** [comment]
I think it's fine to leave it; I'm in favor of more rather than less ways to access things.

**Comment by frewsxcv** [comment]
sounds good to me 👍
