### ISSUE TITLE
consider PEP 257 compliance

### ISSUE THREAD

**Issue by skj3gg** [frewsxcv/python-geojson#50]
Some people don't like it (or don't care) and some do, so I wanted your opinion on being [PEP 257](https://www.python.org/dev/peps/pep-0257/) complaint before taking the time to write all the doc strings.

**Comment by chrisvoncsefalvay** [comment]
I've got some time to work on this and I've gotten a lot of value out of this, so it's only fair I give some back...

**Comment by skj3gg** [comment]
+1 Go for it!
