### ISSUE TITLE
Allow constructing objects like Feature(feature)

### ISSUE THREAD

**Issue by hyperknot** [frewsxcv/python-geojson#55]
In Python most object support creating a new object from an old one, (AFAIK by doing a copy operation), by constructing it in the form of:

```
a = dict(...)
b = dict(a)
```

In geojson it is not supported. If I try to do:

```
f = Feature(...)
f2 = Feature(f)
```

It creates a broken object like:

```
{"geometry": null, "id": {"geometry": null, "properties": {}, "type": "Feature"}, "properties": {}, "type": "Feature"}
```

This would be especially important as geojson is inheriting from `dict`, so ideally it should behave in a similar way.

**Comment by JesseWeinstein** [comment]
Attempting to address this in PR #104

**Comment by frewsxcv** [comment]
completed in https://github.com/frewsxcv/python-geojson/pull/104. will release a new version shortly
