### ISSUE TITLE
geojson.map_coords.__doc___ confusing

### ISSUE THREAD

**Issue by disarticulate** [frewsxcv/python-geojson#75]
I'm doing this test case:
`print(geojson.map_coords.__doc__)`

>     Returns the coordinates from a Geometry after applying the provided
>     function to the tuples.
>     :param func: Function to apply to tuples
>     :type func: function
>     :param obj: A geometry or feature to extract the coordinates from.
>     :type obj: Point, LineString, MultiPoint, MultiLineString, Polygon,
>     MultiPolygon
>     :return: The result of applying the function to each coordinate array.
>     :rtype: list
>     :raises ValueError: if the provided object is not a Geometry.

```
     for item in geoj:
         print(item)
         #geoj_proj = geojson.utils.map_coords(lambda x: conversions.LFtoLongLat(x), item)
         geoj_proj = geojson.utils.map_coords(lambda x: print(x), item)
         break
```

> {"coordinates": [[4493.178634548326, 3454.400914449211], [4483.730689118465, 3449.566045195004], [4500, 3452.474407915964]], "type": "LineString"}
> 4493.178634548326
> 3454.400914449211
> 4483.730689118465
> 3449.566045195004
> 4500
> 3452.474407915964

I expected print(x) to bu a tuple? As the doc says 'after applying the provided function to the tuples. Am I missing something? My conversions.LFtoLongLat expect a tuple, as I'm doing an affine transformation.

**Comment by disarticulate** [comment]
It looks like I don't understand the underlying map issue.

**Comment by frewsxcv** [comment]
[The source for reference](https://github.com/frewsxcv/python-geojson/blob/bfea4a814632806761093eafcd50de27ec013de7/geojson/utils.py#L43-L58)

[Also the documentation in the readme](https://github.com/frewsxcv/python-geojson#map_coords)

```python
    ...
    elif obj['type'] in ['LineString', 'MultiPoint']:
        coordinates = [tuple(map(func, c)) for c in obj['coordinates']]
    ...
```

This code causes `func` to get applied on *every* numeric value within a coordinate for all `coordinates`.

If it were:

```python
    ...
    elif obj['type'] in ['LineString', 'MultiPoint']:
        coordinates = [tuple(map(func, obj['coordinates']))]
    ...
```

Then it would like you say and apply `func` on every coordinate tuple.

If you know a way to make the documentation more clear about this, feel free to open a pull request. Let me know if you have any other issues!

**Comment by disarticulate** [comment]
I've added two pull requests. One to update the documentation to clarify the dimension of the mapping function. Another with a general utility based on the mapping function to take a function which operates on tuples.
