### ISSUE TITLE
Utility method to calculate area from geometry

### ISSUE THREAD

**Issue by nchammas** [frewsxcv/python-geojson#77]
Would it be appropriate to add a utility method to this library that calculates the area of GeoJSON polygons and multipolygons?

I can port it from [this Mapbox Javascript library](https://github.com/mapbox/geojson-area).

**Comment by frewsxcv** [comment]
I think any geometric operations and analysis is beyond the scope of this library. This library is just for dealing with the GeoJSON format. If you want to perform an operation like area, I recommend you look at [shapely](https://github.com/Toblerity/Shapely).

http://toblerity.org/shapely/manual.html?highlight=area#object.area

This library (python-geojson), implements the geo interface, so you should be able to [do something like this](https://github.com/Toblerity/Shapely/blob/e236fc9b9e10c87416c19c9583974e5dfb3ede58/tests/test_geointerface.py#L24-L29) to load a geojson object into shapely.

**Comment by frewsxcv** [comment]
Thanks for the idea though!

**Comment by nchammas** [comment]
OK, thanks for the pointer.
