### ISSUE TITLE
Unicode escape

### ISSUE THREAD

**Issue by abruski** [frewsxcv/python-geojson#83]
Is there equivalent to ensure_ascii=False in this module? It converts utf-8 text to escape sequence.

**Comment by frewsxcv** [comment]
All parameters passed to `geojson.dumps` will also be passed to `json.dumps`, so you should be able to pass `ensure_ascii=False`:

https://github.com/frewsxcv/python-geojson/blob/bfea4a814632806761093eafcd50de27ec013de7/geojson/codec.py#L31-L33

Does this answer your question?

**Comment by frewsxcv** [comment]
Reopen if this is still an issue.
