### ISSUE TITLE
Refer to RFC 7946 in documentation

### ISSUE THREAD

**Issue by xorbug** [frewsxcv/python-geojson#85]
python-geojson library documentation, here on github and on pypi [0], still refers to the original spec [1], which has been obsoleted by RFC 7946 [2].
Thank you.

[0] https://pypi.python.org/pypi/geojson/
[1] http://geojson.org/geojson-spec.html
[2] https://tools.ietf.org/html/rfc7946

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/python-geojson/issues/96
