### ISSUE TITLE
Included JSON encoder can't handle Decimal

### ISSUE THREAD

**Issue by crccheck** [frewsxcv/python-geojson#86]
#### Example

```
from geojson import Point
print(Point((Decimal('0'), Decimal('0'))))
TypeError: Decimal('0') is not JSON serializable
```

Expected behavior:
```
from geojson import Point
print(Point((Decimal('0'), Decimal('0'))))
{"coordinates": ["0", "0"], "type": "Point"}
```

#### Workaround
```
json.dumps(Point((Decimal('0'), Decimal('0'))), cls=AnotherJSONEncoder)
```

**Comment by frewsxcv** [comment]
Serializing `Decimal`s also doesn't work for Python's built-in JSON encoder. For some people, it makes sense to encode `Decimal`s as JSON floats and for others it makes sense to encode as strings. I'm leaning towards suggesting what was said in https://github.com/frewsxcv/python-geojson/issues/49 and make your own encoder to treat `Decimal` however you want it to be treated.

**Comment by crccheck** [comment]
Yeah, I didn't test it, but I'm afraid that going to float then JSON would change the precision of the numbers. That's happened to me in the past. Since precision is important for lat/lng, and I know [Django's JSONEncoder](https://github.com/django/django/blob/master/django/core/serializers/json.py) works with decimal, I opted to stay in `Decimal` as long as possible.

**Comment by frewsxcv** [comment]
I'd recommend subclassing python-geojson's encoder and adding in the appropriate logic to encode `Decimal`s.

**Comment by frewsxcv** [comment]
If you need help with any of that, let me know.
