### ISSUE TITLE
Computing Bounding Boxes

### ISSUE THREAD

**Issue by lucagiovagnoli** [frewsxcv/python-geojson#88]
Is there a way to compute bounding boxes for Geometries and/or Features? 
If not, would you consider merging a potential PR adding this functionality? (in utils or even as object property, we can discuss that).

**Comment by frewsxcv** [comment]
Great idea, though I'm going to redirect you to my answer in https://github.com/frewsxcv/python-geojson/issues/77 regarding geospatial operations.

**Comment by lucagiovagnoli** [comment]
Thanks for the pointer!
